import { IBike } from './interfaceBikes';

export const bikes: Array<IBike> = [
    {
        name: 'Greenway 26M031',
        manufacturer: 'Greenway',
        color: 'green',
        url: './assets/images/1.jpg',
        age: 'adult',
        year: 2020,
        price: 564,
        type: 'mountain',
        amount: 73,
        shoppingCart: false,
        indx: 0,
        popular: true,
    },
    {
        name: 'Stels GTI',
        manufacturer: 'Stels',
        color: 'red',
        url: './assets/images/2.jpg',
        age: 'adult',
        year: 2021,
        price: 550,
        type: 'mountain',
        amount: 50,
        shoppingCart: false,
        indx: 1,
        popular: false,
    },
    {
        name: 'Stels Gadgets15',
        manufacturer: 'Stels',
        color: 'red',
        url: './assets/images/3.jpg',
        age: 'adult',
        year: 2022,
        price: 480,
        type: 'city',
        amount: 22,
        shoppingCart: false,
        indx: 2,
        popular: true,
    },
    {
        name: 'Greenway Kraft 400',
        manufacturer: 'Greenway',
        color: 'blue',
        url: './assets/images/4.jpg',
        age: 'children',
        year: 2021,
        price: 490,
        type: 'city',
        amount: 17,
        shoppingCart: false,
        indx: 3,
        popular: true,
    },
    {
        name: 'Aist 28-130 CKD',
        manufacturer: 'Aist',
        color: 'grey',
        url: './assets/images/5.jpg',
        age: 'adult',
        year: 2019,
        price: 425,
        type: 'road',
        amount: 29,
        shoppingCart: false,
        indx: 4,
        popular: true,
    },
    {
        name: 'Aist Rocky 1.0',
        manufacturer: 'Aist',
        color: 'grey',
        url: './assets/images/6.jpg',
        age: 'teenage',
        year: 2016,
        price: 475,
        type: 'mountain',
        amount: 68,
        shoppingCart: false,
        indx: 5,
        popular: false,
    },
    {
        name: 'Aist MAJESTIC',
        manufacturer: 'Aist',
        color: 'green',
        url: './assets/images/7.jpg',
        age: 'teenage',
        year: 2015,
        price: 652,
        type: 'city',
        amount: 29,
        shoppingCart: false,
        indx: 6,
        popular: true,
    },
    {
        name: 'Stels Jet 18',
        manufacturer: 'Stels',
        color: 'green',
        url: './assets/images/8.jpeg',
        age: 'children',
        year: 2021,
        price: 646,
        type: 'mountain',
        amount: 35,
        shoppingCart: false,
        indx: 7,
        popular: true,
    },
    {
        name: 'Aist Rt-24',
        manufacturer: 'Aist',
        color: 'blue',
        url: './assets/images/9.jpg',
        age: 'teenage',
        year: 2011,
        price: 386,
        type: 'city',
        amount: 62,
        shoppingCart: false,
        indx: 8,
        popular: false,
    },
    {
        name: 'Aist Avenue 1.026',
        manufacturer: 'Aist',
        color: 'white',
        url: './assets/images/10.jpg',
        age: 'adult',
        year: 2011,
        price: 486,
        type: 'city',
        amount: 42,
        shoppingCart: false,
        indx: 9,
        popular: true,
    },
    {
        name: 'Aist Pluto 16',
        manufacturer: 'Aist',
        color: 'yellow',
        url: './assets/images/11.jpg',
        age: 'children',
        year: 2017,
        price: 366,
        type: 'city',
        amount: 52,
        shoppingCart: false,
        indx: 10,
        popular: true,
    },
    {
        name: 'Aist Pirate 1.0',
        manufacturer: 'Aist',
        color: 'yellow',
        url: './assets/images/12.jpg',
        age: 'teenage',
        year: 2012,
        price: 386,
        type: 'city',
        amount: 42,
        shoppingCart: false,
        indx: 11,
        popular: true,
    },
    {
        name: 'Stels Wind z010',
        manufacturer: 'Stels',
        color: 'blue',
        url: './assets/images/13.jpg',
        age: 'children',
        year: 2016,
        price: 396,
        type: 'city',
        amount: 52,
        shoppingCart: false,
        indx: 12,
        popular: false,
    },
    {
        name: 'Greenway 24S006-L',
        manufacturer: 'Greenway',
        color: 'grey',
        url: './assets/images/14.jpg',
        age: 'teenage',
        year: 2011,
        price: 596,
        type: 'mountain',
        amount: 40,
        shoppingCart: false,
        indx: 13,
        popular: true,
    },
    {
        name: 'Aist Avatar Disc ',
        manufacturer: 'Aist',
        color: 'yellow',
        url: './assets/images/15.jpg',
        age: 'teenage',
        year: 2015,
        price: 542,
        type: 'mountain',
        amount: 53,
        shoppingCart: false,
        indx: 14,
        popular: true,
    },
    {
        name: 'Greenway Windrunner',
        manufacturer: 'Greenway',
        color: 'red',
        url: './assets/images/16.jpg',
        age: 'teenage',
        year: 2012,
        price: 602,
        type: 'mountain',
        amount: 45,
        shoppingCart: false,
        indx: 15,
        popular: true,
    },
    {
        name: 'Stels Jet Z010',
        manufacturer: 'Stels',
        color: 'red',
        url: './assets/images/17.jpg',
        age: 'children',
        year: 2005,
        price: 374,
        type: 'city',
        amount: 46,
        shoppingCart: false,
        indx: 16,
        popular: false,
    },
    {
        name: 'Stels Navigator v010',
        manufacturer: 'Stels',
        color: 'blue',
        url: './assets/images/18.jpeg',
        age: 'adult',
        year: 2002,
        price: 384,
        type: 'road',
        amount: 37,
        shoppingCart: false,
        indx: 17,
        popular: false,
    },
    {
        name: 'Stels Aggressor V010',
        manufacturer: 'Stels',
        color: 'grey',
        url: './assets/images/19.jpeg',
        age: 'teenage',
        year: 2011,
        price: 554,
        type: 'mountain',
        amount: 49,
        shoppingCart: false,
        indx: 18,
        popular: true,
    },
    {
        name: 'Stels 27.5" Adrenalin',
        manufacturer: 'Stels',
        color: 'blue',
        url: './assets/images/20.jpg',
        age: 'teenage',
        year: 2015,
        price: 654,
        type: 'mountain',
        amount: 79,
        shoppingCart: false,
        indx: 19,
        popular: false,
    },
    {
        name: 'Stels Focus V 26',
        manufacturer: 'Stels',
        color: 'blue',
        url: './assets/images/21.jpeg',
        age: 'adult',
        year: 2010,
        price: 684,
        type: 'mountain',
        amount: 49,
        shoppingCart: false,
        indx: 20,
        popular: true,
    },
    {
        name: 'Greenway 4919m 24',
        manufacturer: 'Greenway',
        color: 'red',
        url: './assets/images/22.jpg',
        age: 'teenage',
        year: 2017,
        price: 586,
        type: 'mountain',
        amount: 55,
        shoppingCart: false,
        indx: 21,
        popular: true,
    },
    {
        name: 'Greenway NM24',
        manufacturer: 'Greenway',
        color: 'blue',
        url: './assets/images/23.jpg',
        age: 'teenage',
        year: 2016,
        price: 686,
        type: 'mountain',
        amount: 59,
        shoppingCart: false,
        indx: 22,
        popular: true,
    },
    {
        name: 'Greenway WHit22',
        manufacturer: 'Greenway',
        color: 'white',
        url: './assets/images/24.jpg',
        age: 'teenage',
        year: 2014,
        price: 560,
        type: 'city',
        amount: 67,
        shoppingCart: false,
        indx: 23,
        popular: false,
    },
];
